export const translations = {
	locale: "en",
	Navbar: {
		"HOME": "Home",
		"INICIO": "Inicio",
		"ABOUT": "About",
		"SOBRE": "Sobre",
		"SERVICE": "Service",
		"SERVICIOS": "Servicios",
		"PORTFOLIO": "Portfolio",
		"PORTAFOLIO": "Portafolio",
		"CONTACT": "Contact",
		"CONTACTO": "Contacto",
	},
	Header: {
		"WELCOME": "WELCOME TO MY PORTFOLIO",
		"BIENVENIDO": "BIENVENIDO A MI PORTAFOLIO",
		"HI": "Hi, I’m Omar",
		"HOLA": "Hola, soy Omar",
		"DEVELOPER": "FullStack Developer",
		"DESARROLLADOR": "Desarrollador FullStack",
		"DEVELOPER_FRONTEND": "Frontend Developer",
		"DESARROLLADOR_FRONTEND": "Desarrollador Frontend",
		"DEVELOPER_BACKEND": "Backend Developer",
		"DESARROLLADOR_BACKEND": "Desarrollador Backend",
	},
	AboutMe: {
		"TITLE": "About Me",
		"TITULO": "Sobre mí",
		"DESCRIPTION": "I am a web developer and an engineering student at computer science, with experience in the development of applications and web pages, I consider myself a pro-active person, focused on detail, always in looking for the next challenge, with great motivation to learn something new every day.",
		"DESCRIPCION": "Soy Desarrollador web y estudiante de ingeniería en informática, con experiencia en el desarrollo de aplicaciones y paginas web, me considero una persona pro-activa, enfocada al detalle, siempre enbusca del siguiente reto, con una gran motivación para a prender algo nuevo cada día.",
		"MAIN_SKILLS": "Main skills",
		"HABILIDADES": "Habilidades principales",
		"EDUCATION": "Education",
		"EDUCACION": "Educacion",
		"LAYAUT": "Layout of web pages and applications.",
		"DISEÑO": "Diseño de páginas web y aplicaciones.",
		"SKILL_REACT": "I use React for interactivity with the frontend.",
		"HABILIDAD_REACT": "Utilizo React para interactuar con el frontend.",
		"SKILL_BACKEND": "Development using these technologies to create the backend of the applications.",
		"HABILIDAD_BACKEND": "Desarrollo utilizando estas tecnologías para crear el backend de las aplicaciones.",
	},
	MyService: {
		"MYSERVICE": "My Service",
		"MISERVICIOS": "Mi servicios",
		"DESCRIPTION": "I have experience developing robust apps and websites for high-volume devices. I am proficient at building and maintaining professional relationships.",
		"DESCRIPCION": "Tengo experiencia en el desarrollo de sitios web y aplicaciones robustas para dispositivos de gran volumen. Soy competente en la construcción y el mantenimiento de relaciones profesionales.",
		"CARD_TITLE_FIRST": "Responsive web design",
		"TITULO_PRIMERA_TARGETA": "Diseño web adaptable",
		"CARD_FIRST_TEXT": "Build applications that adapt to different mobile and desktop devices.",
		"TEXTO_PRIMERA_TARJETA": "Creo aplicaciones que se adapten a diferentes dispositivos móviles y de escritorio.",
		"CARD_TITLE_SECOND": "Fron-tend Developer",
		"TITULO_SEGUNDA_TARGETA": "Desarrollador Fron-tend",
		"CARD_SECOND_TEXT": "Create websites, applications and commerce sites, where different technologies are used on the client side for the interaction with the website.",
		"TEXTO_SEGUNDA_TARJETA": "Crear sitios web, aplicaciones y sitios comerciales, donde se utilizan diferentes tecnologías del lado del cliente para la interacción con el sitio web.",
		"CARD_TITLE_THIRD": "Backend Developer",
		"TITULO_TERCERA_TARGETA": "Desarrollador Backend",
		"CARD_THIRD_TEXT": "Development of backend services, Rest Apis, with Node and MongoDB in the backend.",
		"TEXTO_TERCERA_TARJETA": "Desarrollo de servicios backend, Rest Apis, con Node y MongoDB en el backend.",
	},
	Technologies: {
		"TITLE": "Frameworks and Technologies",
		"TITULO": "Marcos y tecnologías",
		"DESCRIPTION": "These are some of the libraries, technologies and languages ​​that I have used in the projects that I have done.",
		"DESCRIPCION": "Estas son algunas de las bibliotecas, tecnologías y lenguajes que he utilizado en los proyectos que he realizado.",
	},
	Works: {
		"TITLE": "My Recent Work",
		"TITULO": "Mis trabajos",
		"DESCRIPTION": "I am going to show the projects that I have done during this time. Some of them are personal others for some clients.",
		"DESCRIPCION": "Les voy a mostrar los proyectos que he realizado durante este tiempo. Algunos de ellos son personales, otros para algunos clientes.",
	},
	HireMe: {
		"TITLE": "Contact Me",
		"TITULO": "Contáctame",
		"DESCRIPTION": "I am available for freelance work. Contact with me via phone:",
		"DESCRIPCION": "Estoy disponible para el trabajo independiente. Contactese conmigo por teléfono:",
		"placeholderName": "Your Name",
		"placeholderNombre": "Tu Nombre",
		"placeholderEmail": "Your Email",
		"placeholderCorreo": "Tu Correo",
		"placeholderSubject": "Write a Subject",
		"placeholderTema": "Escribe un tema",
		"placeholderMessage": "Your Message",
		"placeholderMensaje": "Tu Mensaje",
	},
	AboutProjects: {
		"ABOUT": "About",
		"SOBRE": "Sobre",
		"DEMO": "Below you can see a demo of the project:",
		"DEMOSTRACION": "A continuación puede ver una demostración del proyecto:",
		"SITE_PROJECT": "Project site",
		"SITIO_PROYECTO": "Sitio del proyecto",
	},
}